version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: iurelen/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static/
      - media:/media/
  frontend:
    image: iurelen/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static/
  gateway:
    image: iurelen/foodgram_gateway
    env_file: .env
    volumes:
      - static:/staticfiles/
      - media:/media/
    ports:
      - 8080:80